// pages/classify/classify.js
Page({

  /**
   * 页面的初始数据
   */
  data: {
    list: [{
        id: 1,
        text: '热门推荐',
        text1: '热门分类',
        bt1: [{
          id: 1,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 2,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 3,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 4,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 5,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 6,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 7,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 8,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 9,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 10,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 11,
          src: '/images/kt.jpg',
          nr: '空调'
        }, ]
      },
      {
        id: 2,
        text: '手机数码',
        text1: '热门品牌',
        text2: '摄影摄像',
        bt1: [{
          id: 1,
          src: '/images/xm.png',
          nr: '小米'
        }, {
          id: 2,
          src: '/images/xm.png',
          nr: '小米'
        }, {
          id: 3,
          src: '/images/xm.png',
          nr: '小米'
        }, {
          id: 4,
          src: '/images/xm.png',
          nr: '小米'
        }, {
          id: 5,
          src: '/images/xm.png',
          nr: '小米'
        }, {
          id: 6,
          src: '/images/xm.png',
          nr: '小米'
        }, {
          id: 7,
          src: '/images/xm.png',
          nr: '小米'
        }, {
          id: 8,
          src: '/images/xm.png',
          nr: '小米'
        }],
        bt2: [{
          id: 1,
          src: '/images/df.jpg',
          nr: '单反相机'
        }, {
          id: 2,
          src: '/images/df.jpg',
          nr: '单反相机'
        }, {
          id: 3,
          src: '/images/df.jpg',
          nr: '单反相机'
        }, {
          id: 4,
          src: '/images/df.jpg',
          nr: '单反相机'
        }, {
          id: 5,
          src: '/images/df.jpg',
          nr: '单反相机'
        }, {
          id: 6,
          src: '/images/df.jpg',
          nr: '单反相机'
        }, {
          id: 7,
          src: '/images/df.jpg',
          nr: '单反相机'
        }, {
          id: 8,
          src: '/images/df.jpg',
          nr: '单反相机'
        }]
      },
      {
        id: 3,
        text: '京东超市',
        text1: '休闲零食',
        text2: '粮油调味',
        text3: '水饮茗茶',
        bt1: [{
          id: 1,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 2,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 3,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 4,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 5,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 6,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }],
        bt2: [{
          id: 1,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 2,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 3,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 4,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 5,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 6,
          src: '/images/dm.jpg',
          nr: '大米'
        }],
        bt3: [{
          id: 1,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 2,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 3,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 4,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 5,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 6,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }]
      },
      {
        id: 4,
        text: '家用电器',
        text1: '热门分类',
        bt1: [{
          id: 1,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 2,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 3,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 4,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 5,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 6,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 7,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 8,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 9,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 10,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 11,
          src: '/images/kt.jpg',
          nr: '空调'
        }, ]
      },
      {
        id: 5,
        text: '电脑办公',
        text1: '热门品牌',
        text2: '摄影摄像',
        bt1: [{
          id: 1,
          src: '/images/xm.png',
          nr: '小米'
        }, {
          id: 2,
          src: '/images/xm.png',
          nr: '小米'
        }, {
          id: 3,
          src: '/images/xm.png',
          nr: '小米'
        }, {
          id: 4,
          src: '/images/xm.png',
          nr: '小米'
        }, {
          id: 5,
          src: '/images/xm.png',
          nr: '小米'
        }, {
          id: 6,
          src: '/images/xm.png',
          nr: '小米'
        }, {
          id: 7,
          src: '/images/xm.png',
          nr: '小米'
        }, {
          id: 8,
          src: '/images/xm.png',
          nr: '小米'
        }],
        bt2: [{
          id: 1,
          src: '/images/df.jpg',
          nr: '单反相机'
        }, {
          id: 2,
          src: '/images/df.jpg',
          nr: '单反相机'
        }, {
          id: 3,
          src: '/images/df.jpg',
          nr: '单反相机'
        }, {
          id: 4,
          src: '/images/df.jpg',
          nr: '单反相机'
        }, {
          id: 5,
          src: '/images/df.jpg',
          nr: '单反相机'
        }, {
          id: 6,
          src: '/images/df.jpg',
          nr: '单反相机'
        }, {
          id: 7,
          src: '/images/df.jpg',
          nr: '单反相机'
        }, {
          id: 8,
          src: '/images/df.jpg',
          nr: '单反相机'
        }]
      },
      {
        id: 6,
        text: '玩具乐器',
        text1: '休闲零食',
        text2: '粮油调味',
        text3: '水饮茗茶',
        bt1: [{
          id: 1,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 2,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 3,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 4,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 5,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 6,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }],
        bt2: [{
          id: 1,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 2,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 3,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 4,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 5,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 6,
          src: '/images/dm.jpg',
          nr: '大米'
        }],
        bt3: [{
          id: 1,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 2,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 3,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 4,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 5,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 6,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }]
      },
      {
        id: 7,
        text: '家居厨具',
        text1: '热门分类',
        bt1: [{
          id: 1,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 2,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 3,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 4,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 5,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 6,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 7,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 8,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 9,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 10,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 11,
          src: '/images/kt.jpg',
          nr: '空调'
        }, ]
      },
      {
        id: 8,
        text: '家具家装',
        text1: '热门分类',
        bt1: [{
          id: 1,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 2,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 3,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 4,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 5,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 6,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 7,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 8,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 9,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 10,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 11,
          src: '/images/kt.jpg',
          nr: '空调'
        }, ]
      },
      {
        id: 9,
        text: '男装',
        text1: '热门分类',
        bt1: [{
          id: 1,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 2,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 3,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 4,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 5,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 6,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 7,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 8,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 9,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 10,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 11,
          src: '/images/kt.jpg',
          nr: '空调'
        }, ]
      },
      {
        id: 10,
        text: '男鞋',
        text1: '热门分类',
        bt1: [{
          id: 1,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 2,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 3,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 4,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 5,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 6,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 7,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 8,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 9,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 10,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 11,
          src: '/images/kt.jpg',
          nr: '空调'
        }, ]
      },
      {
        id: 11,
        text: '女装',
        text1: '热门分类',
        bt1: [{
          id: 1,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 2,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 3,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 4,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 5,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 6,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 7,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 8,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 9,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 10,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 11,
          src: '/images/kt.jpg',
          nr: '空调'
        }, ]
      },
      {
        id: 12,
        text: '女鞋',
        text1: '热门分类',
        bt1: [{
          id: 1,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 2,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 3,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 4,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 5,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 6,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 7,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 8,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 9,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 10,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 11,
          src: '/images/kt.jpg',
          nr: '空调'
        }, ]
      },
      {
        id: 13,
        text: '美妆护肤',
        text1: '热门分类',
        bt1: [{
          id: 1,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 2,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 3,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 4,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 5,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 6,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 7,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 8,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 9,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 10,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 11,
          src: '/images/kt.jpg',
          nr: '空调'
        }, ]
      },
      {
        id: 14,
        text: '医药保健',
        text1: '热门分类',
        bt1: [{
          id: 1,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 2,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 3,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 4,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 5,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 6,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 7,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 8,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 9,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 10,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 11,
          src: '/images/kt.jpg',
          nr: '空调'
        }, ]
      },
      {
        id: 15,
        text: '酒水饮料',
        text1: '热门分类',
        bt1: [{
          id: 1,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 2,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 3,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 4,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 5,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 6,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 7,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 8,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 9,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 10,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 11,
          src: '/images/kt.jpg',
          nr: '空调'
        }, ]
      },
      {
        id: 16,
        text: '运动户外',
        text1: '热门分类',
        bt1: [{
          id: 1,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 2,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 3,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 4,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 5,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 6,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 7,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 8,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 9,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 10,
          src: '/images/kt.jpg',
          nr: '空调'
        }, {
          id: 11,
          src: '/images/kt.jpg',
          nr: '空调'
        }, ]
      },
      {
        id: 17,
        text: '汽车生活',
        text1: '休闲零食',
        text2: '粮油调味',
        text3: '水饮茗茶',
        bt1: [{
          id: 1,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 2,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 3,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 4,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 5,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 6,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }],
        bt2: [{
          id: 1,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 2,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 3,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 4,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 5,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 6,
          src: '/images/dm.jpg',
          nr: '大米'
        }],
        bt3: [{
          id: 1,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 2,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 3,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 4,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 5,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 6,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }]
      },
      {
        id: 18,
        text: '礼品鲜花',
        text1: '休闲零食',
        text2: '粮油调味',
        text3: '水饮茗茶',
        bt1: [{
          id: 1,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 2,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 3,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 4,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 5,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 6,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }],
        bt2: [{
          id: 1,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 2,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 3,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 4,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 5,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 6,
          src: '/images/dm.jpg',
          nr: '大米'
        }],
        bt3: [{
          id: 1,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 2,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 3,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 4,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 5,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 6,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }]
      },
      {
        id: 19,
        text: '京东国际',
        text1: '休闲零食',
        text2: '粮油调味',
        text3: '水饮茗茶',
        bt1: [{
          id: 1,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 2,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 3,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 4,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 5,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 6,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }],
        bt2: [{
          id: 1,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 2,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 3,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 4,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 5,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 6,
          src: '/images/dm.jpg',
          nr: '大米'
        }],
        bt3: [{
          id: 1,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 2,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 3,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 4,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 5,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 6,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }]
      },
      {
        id: 20,
        text: '宠物生活',
        text1: '休闲零食',
        text2: '粮油调味',
        text3: '水饮茗茶',
        bt1: [{
          id: 1,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 2,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 3,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 4,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 5,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 6,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }],
        bt2: [{
          id: 1,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 2,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 3,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 4,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 5,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 6,
          src: '/images/dm.jpg',
          nr: '大米'
        }],
        bt3: [{
          id: 1,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 2,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 3,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 4,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 5,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 6,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }]
      },
      {
        id: 21,
        text: '二手商品',
        text1: '休闲零食',
        text2: '粮油调味',
        text3: '水饮茗茶',
        bt1: [{
          id: 1,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 2,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 3,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 4,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 5,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 6,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }],
        bt2: [{
          id: 1,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 2,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 3,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 4,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 5,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 6,
          src: '/images/dm.jpg',
          nr: '大米'
        }],
        bt3: [{
          id: 1,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 2,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 3,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 4,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 5,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 6,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }]
      },
      {
        id: 22,
        text: '拍卖',
        text1: '休闲零食',
        text2: '粮油调味',
        text3: '水饮茗茶',
        bt1: [{
          id: 1,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 2,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 3,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 4,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 5,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 6,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }],
        bt2: [{
          id: 1,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 2,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 3,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 4,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 5,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 6,
          src: '/images/dm.jpg',
          nr: '大米'
        }],
        bt3: [{
          id: 1,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 2,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 3,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 4,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 5,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 6,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }]
      },
      {
        id: 23,
        text: '箱包手袋',
        text1: '休闲零食',
        text2: '粮油调味',
        text3: '水饮茗茶',
        bt1: [{
          id: 1,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 2,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 3,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 4,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 5,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 6,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }],
        bt2: [{
          id: 1,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 2,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 3,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 4,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 5,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 6,
          src: '/images/dm.jpg',
          nr: '大米'
        }],
        bt3: [{
          id: 1,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 2,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 3,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 4,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 5,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 6,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }]
      },
      {
        id: 24,
        text: '钟表珠宝',
        text1: '休闲零食',
        text2: '粮油调味',
        text3: '水饮茗茶',
        bt1: [{
          id: 1,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 2,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 3,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 4,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 5,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 6,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }],
        bt2: [{
          id: 1,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 2,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 3,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 4,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 5,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 6,
          src: '/images/dm.jpg',
          nr: '大米'
        }],
        bt3: [{
          id: 1,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 2,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 3,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 4,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 5,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 6,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }]
      },
      {
        id: 25,
        text: '农资绿植',
        text1: '休闲零食',
        text2: '粮油调味',
        text3: '水饮茗茶',
        bt1: [{
          id: 1,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 2,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 3,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 4,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 5,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 6,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }],
        bt2: [{
          id: 1,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 2,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 3,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 4,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 5,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 6,
          src: '/images/dm.jpg',
          nr: '大米'
        }],
        bt3: [{
          id: 1,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 2,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 3,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 4,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 5,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 6,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }]
      },
      {
        id: 26,
        text: '生活旅行',
        text1: '休闲零食',
        text2: '粮油调味',
        text3: '水饮茗茶',
        bt1: [{
          id: 1,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 2,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 3,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 4,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 5,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 6,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }],
        bt2: [{
          id: 1,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 2,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 3,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 4,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 5,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 6,
          src: '/images/dm.jpg',
          nr: '大米'
        }],
        bt3: [{
          id: 1,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 2,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 3,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 4,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 5,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 6,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }]
      },
      {
        id: 27,
        text: '奢侈品',
        text1: '休闲零食',
        text2: '粮油调味',
        text3: '水饮茗茶',
        bt1: [{
          id: 1,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 2,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 3,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 4,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 5,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 6,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }],
        bt2: [{
          id: 1,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 2,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 3,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 4,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 5,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 6,
          src: '/images/dm.jpg',
          nr: '大米'
        }],
        bt3: [{
          id: 1,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 2,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 3,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 4,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 5,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 6,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }]
      },
      {
        id: 28,
        text: '计生情趣',
        text1: '休闲零食',
        text2: '粮油调味',
        text3: '水饮茗茶',
        bt1: [{
          id: 1,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 2,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 3,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 4,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 5,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 6,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }],
        bt2: [{
          id: 1,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 2,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 3,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 4,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 5,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 6,
          src: '/images/dm.jpg',
          nr: '大米'
        }],
        bt3: [{
          id: 1,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 2,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 3,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 4,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 5,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 6,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }]
      },
      {
        id: 29,
        text: '艺术邮币',
        text1: '休闲零食',
        text2: '粮油调味',
        text3: '水饮茗茶',
        bt1: [{
          id: 1,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 2,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 3,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 4,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 5,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 6,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }],
        bt2: [{
          id: 1,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 2,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 3,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 4,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 5,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 6,
          src: '/images/dm.jpg',
          nr: '大米'
        }],
        bt3: [{
          id: 1,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 2,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 3,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 4,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 5,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 6,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }]
      },
      {
        id: 30,
        text: '特产馆',
        text1: '休闲零食',
        text2: '粮油调味',
        text3: '水饮茗茶',
        bt1: [{
          id: 1,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 2,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 3,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 4,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 5,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 6,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }],
        bt2: [{
          id: 1,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 2,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 3,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 4,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 5,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 6,
          src: '/images/dm.jpg',
          nr: '大米'
        }],
        bt3: [{
          id: 1,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 2,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 3,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 4,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 5,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 6,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }]
      },
      {
        id: 31,
        text: '京东金融',
        text1: '休闲零食',
        text2: '粮油调味',
        text3: '水饮茗茶',
        bt1: [{
          id: 1,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 2,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 3,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 4,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 5,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 6,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }],
        bt2: [{
          id: 1,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 2,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 3,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 4,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 5,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 6,
          src: '/images/dm.jpg',
          nr: '大米'
        }],
        bt3: [{
          id: 1,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 2,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 3,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 4,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 5,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 6,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }]
      },
      {
        id: 32,
        text: '国际名牌',
        text1: '休闲零食',
        text2: '粮油调味',
        text3: '水饮茗茶',
        bt1: [{
          id: 1,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 2,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 3,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 4,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 5,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 6,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }],
        bt2: [{
          id: 1,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 2,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 3,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 4,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 5,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 6,
          src: '/images/dm.jpg',
          nr: '大米'
        }],
        bt3: [{
          id: 1,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 2,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 3,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 4,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 5,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 6,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }]
      },
      {
        id: 33,
        text: '房产',
        text1: '休闲零食',
        text2: '粮油调味',
        text3: '水饮茗茶',
        bt1: [{
          id: 1,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 2,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 3,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 4,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 5,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 6,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }],
        bt2: [{
          id: 1,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 2,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 3,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 4,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 5,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 6,
          src: '/images/dm.jpg',
          nr: '大米'
        }],
        bt3: [{
          id: 1,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 2,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 3,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 4,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 5,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 6,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }]
      },
      {
        id: 34,
        text: '工业品',
        text1: '休闲零食',
        text2: '粮油调味',
        text3: '水饮茗茶',
        bt1: [{
          id: 1,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 2,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 3,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 4,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 5,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }, {
          id: 6,
          src: '/images/ls.jpg',
          nr: '休闲零食'
        }],
        bt2: [{
          id: 1,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 2,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 3,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 4,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 5,
          src: '/images/dm.jpg',
          nr: '大米'
        }, {
          id: 6,
          src: '/images/dm.jpg',
          nr: '大米'
        }],
        bt3: [{
          id: 1,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 2,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 3,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 4,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 5,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }, {
          id: 6,
          src: '/images/mm.jpg',
          nr: '牛奶制品'
        }]
      }
    ],
    flag: 1,
    gotop: 0
  },
  jiaodian(e) {
    // console.log(e.currentTarget.offsetTop)
    var index = e.target.dataset.id
    this.setData({
      flag: index,
      gotop: e.currentTarget.offsetTop
    })
  },
  go() {
    wx.navigateTo({
      url: '/pages/search/search'
    })
  },
  /**
   * 生命周期函数--监听页面加载
   */
  onLoad(options) {},

  /**
   * 生命周期函数--监听页面初次渲染完成
   */
  onReady() {

  },

  /**
   * 生命周期函数--监听页面显示
   */
  onShow() {

  },

  /**
   * 生命周期函数--监听页面隐藏
   */
  onHide() {

  },

  /**
   * 生命周期函数--监听页面卸载
   */
  onUnload() {

  },

  /**
   * 页面相关事件处理函数--监听用户下拉动作
   */
  onPullDownRefresh() {

  },

  /**
   * 页面上拉触底事件的处理函数
   */
  onReachBottom() {

  },

  /**
   * 用户点击右上角分享
   */
  onShareAppMessage() {

  }
})